<?xml version="1.0" ?>

<!DOCTYPE Arrondissements [

<!ELEMENT Arrondissements (Arrondissement+) >
<!ELEMENT Arrondissement (Tournage)>
<!ELEMENT Tournage (Titre, Realisateur, Organisme_demandeur, Adresse)>
<!ATTLIST Tournage type (SERIE_TELEVISEE|LONG_METRAGE|TELEFILM) #REQUIRED>
<!ELEMENT Titre (#PCDATA)>
<!ELEMENT Realisateur (#PCDATA)>
<!ELEMENT Organisme_demandeur (#PCDATA)>
<!ELEMENT Adresse (#PCDATA)>
<!ATTLIST Adresse coordonnees CDATA #IMPLIED
date_debut CDATA #REQUIRED
date_fin CDATA #REQUIRED>
	
]>

<Arrondissements>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LEO MATTEI/14 ET 15</Titre>
      <Realisateur>NICOLAS HERDT</Realisateur>
      <Organisme_demandeur>LGM CINEMA</Organisme_demandeur>
      <Adresse coordonnees="48.84726,2.365669" date_debut="2016-10-06" date_fin="2016-10-06">PONT  MORLAND</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>MUNCH</Titre>
      <Realisateur>NICOLAS GUICHETEAU</Realisateur>
      <Organisme_demandeur>EXILENE FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.852888,2.352022" date_debut="2016-10-28" date_fin="2016-10-28">1  QUAI  AUX FLEURS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.855157,2.362596" date_debut="2016-02-26" date_fin="2016-02-26">RUE  CARON</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.85194,2.365872" date_debut="2016-02-26" date_fin="2016-02-26">IMPASSE  DE LA POISSONNERIE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>KANTOR</Titre>
      <Realisateur>JAN HRYNIAK</Realisateur>
      <Organisme_demandeur>BLINK FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.853089,2.363695" date_debut="2016-03-15" date_fin="2016-03-15">RUE  BEAUTREILLIS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.855349,2.363274" date_debut="2016-02-26" date_fin="2016-02-26">RUE  NECKER</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>CHRONIQUES PARISIENNES</Titre>
      <Realisateur>ZABOU BREITMAN</Realisateur>
      <Organisme_demandeur>LES FILMS DU KIOSQUE</Organisme_demandeur>
      <Adresse coordonnees="48.856204,2.353258" date_debut="2016-10-01" date_fin="2016-10-01">RUE  LOBAU</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.854714,2.354821" date_debut="2016-02-26" date_fin="2016-02-26">PARVIS  DE L'HOTEL DE VILLE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>MADAME</Titre>
      <Realisateur>AMANDA STHERS</Realisateur>
      <Organisme_demandeur>LGM FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.85856,2.357017" date_debut="2016-07-22" date_fin="2016-07-22">PONT  AU DOUBLE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>CA C'EST LA FAMILLE</Titre>
      <Realisateur>TEDDY LUSSI MODESTE</Realisateur>
      <Organisme_demandeur>KAZAK PRODUCTIONS</Organisme_demandeur>
      <Adresse coordonnees="48.860043,2.353715" date_debut="2016-09-06" date_fin="2016-09-06">RUE  SIMON LE FRANC</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>120 BATTEMENTS PAR MINUTE</Titre>
      <Realisateur>ROBIN CAMPILLO</Realisateur>
      <Organisme_demandeur>LES FILMS DE PIERRE</Organisme_demandeur>
      <Adresse coordonnees="48.858822,2.352329" date_debut="2016-09-13" date_fin="2016-09-13">12  RUE  DU RENARD</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.852279,2.351269" date_debut="2016-05-18" date_fin="2016-05-19">SQUARE  LOUIS XIII</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>ON THE FRENCH RIVIERA</Titre>
      <Realisateur>ALAN SWYER</Realisateur>
      <Organisme_demandeur>BELLE EPOQUE FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.853713,2.351366" date_debut="2016-08-29" date_fin="2016-08-29">RUE  DES CHANTRES</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>RODIN</Titre>
      <Realisateur>JACQUES DOILLON</Realisateur>
      <Organisme_demandeur>LES FILMS DU LENDEMAIN</Organisme_demandeur>
      <Adresse coordonnees="48.855033,2.356798" date_debut="2016-05-29" date_fin="2016-06-03">28  RUE  GEOFFROY L'ASNIER</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>CHRONIQUES PARISIENNES</Titre>
      <Realisateur>ZABOU BREITMAN</Realisateur>
      <Organisme_demandeur>LES FILMS DU KIOSQUE</Organisme_demandeur>
      <Adresse coordonnees="48.857861,2.353417" date_debut="2016-10-01" date_fin="2016-10-01">40  RUE  DE LA VERRERIE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>IRIS/EX CHAOS</Titre>
      <Realisateur>JALIL LESPERT</Realisateur>
      <Organisme_demandeur>WY PRODUCTIONS</Organisme_demandeur>
      <Adresse coordonnees="48.854978,2.365625" date_debut="2016-02-18" date_fin="2016-02-18">PLACE  DES VOSGES</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>MONSIEUR ET MADAME ADELMAN</Titre>
      <Realisateur>NICOLAS BEDOS</Realisateur>
      <Organisme_demandeur>LES FILMS DU KIOSQUE</Organisme_demandeur>
      <Adresse coordonnees="0" date_debut="2016-03-07" date_fin="2016-03-07">MAIRIE  DU 14EME (SALLE DES MARIAGES)</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>LA DOULEUR</Titre>
      <Realisateur>EMMANUEL FINKIEL</Realisateur>
      <Organisme_demandeur>LES FILMS DU POISSON</Organisme_demandeur>
      <Adresse coordonnees="48.853542,2.347221" date_debut="2016-09-02" date_fin="2016-09-02">PLACE  JEAN PAUL II</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.851849,2.356353" date_debut="2016-04-26" date_fin="2016-04-26">PONT  SAINT LOUIS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>THE PACKAGE</Titre>
      <Realisateur>CHANG KEUN CHUN</Realisateur>
      <Organisme_demandeur>BH PARIS MEDIA PRODUCTIONS</Organisme_demandeur>
      <Adresse coordonnees="48.852216,2.352057" date_debut="2016-10-21" date_fin="2016-10-21">PONT  DE L'ARCHEVECHE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LES 7 NAINS ET MOI</Titre>
      <Realisateur>DAMIEN MARIC</Realisateur>
      <Organisme_demandeur>METHOD FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.853542,2.347221" date_debut="2016-02-17" date_fin="2016-02-17">PLACE  JEAN PAUL II/PARIVS NOTRE DAME</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>ENGRENAGES/SAISON 6/N° 1 A 6</Titre>
      <Realisateur>FREDERIC JARDIN</Realisateur>
      <Organisme_demandeur>SON ET LUMIERE</Organisme_demandeur>
      <Adresse coordonnees="48.854342,2.347729" date_debut="2016-08-08" date_fin="2016-08-09">1  PLACE  DU PARVIS DE NOTRE DAME</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.855335,2.355315" date_debut="2016-06-02" date_fin="2016-06-02">RUE  DES BARRES</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>MARIAGE BLANC</Titre>
      <Realisateur>TAREK BOUDALI</Realisateur>
      <Organisme_demandeur>AXEL FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.853542,2.347221" date_debut="2016-09-15" date_fin="2016-09-15">PARVIS  DE NOTRE DAME</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LEO MATTEI/14 ET 15</Titre>
      <Realisateur>NICOLAS HERDT</Realisateur>
      <Organisme_demandeur>LGM CINEMA</Organisme_demandeur>
      <Adresse coordonnees="48.848397,2.365936" date_debut="2016-10-06" date_fin="2016-10-06">5/9  BOULEVARD  BOURDON</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LIANG SHENG</Titre>
      <Realisateur>LIU CHUN-CHIEN</Realisateur>
      <Organisme_demandeur>KANZAMAN FRANCE</Organisme_demandeur>
      <Adresse coordonnees="48.859772,2.351419" date_debut="2016-12-13" date_fin="2016-12-13">PLACE  IGOR STRAVINSKY</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="TELEFILM">
      <Titre>JE VOULAIS JUSTE RENTRER CHEZ MOI</Titre>
      <Realisateur>YVES RENIER</Realisateur>
      <Organisme_demandeur>CHABRAQUE PRODUCTIONS</Organisme_demandeur>
      <Adresse coordonnees="48.854342,2.347729" date_debut="2016-12-06" date_fin="2016-12-06">1  RUE  DU PARVIS DE NOTRE DAME</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>LE REDOUTABLE</Titre>
      <Realisateur>MICHEL HAZANAVICIUS</Realisateur>
      <Organisme_demandeur>LES COMPAGNONS DU CINEMA</Organisme_demandeur>
      <Adresse coordonnees="48.849125,2.365551" date_debut="2016-08-24" date_fin="2016-08-24">RUE  CRILLON</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>LOLA PATER</Titre>
      <Realisateur>NADIR MOKNECHE</Realisateur>
      <Organisme_demandeur>BLUE MONDAY PRODUCTIONS</Organisme_demandeur>
      <Adresse coordonnees="48.852564,2.36447" date_debut="2016-04-28" date_fin="2016-04-28">26  RUE  DU PETIT MUSC</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LIANG SHENG</Titre>
      <Realisateur>LIU CHUN-CHIEN</Realisateur>
      <Organisme_demandeur>KANZAMAN FRANCE</Organisme_demandeur>
      <Adresse coordonnees="48.852279,2.351269" date_debut="2016-12-11" date_fin="2016-12-11">SQUARE  LOUIS XIII</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.853542,2.347221" date_debut="2016-04-26" date_fin="2016-04-26">PARVIS  DE NOTRE DAME</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.855368,2.355793" date_debut="2016-05-20" date_fin="2016-05-21">PONT  LOUIS PHILIPPE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>IN AMERICA</Titre>
      <Realisateur>VINCENT PRIMAULT</Realisateur>
      <Organisme_demandeur>MAKING PROD</Organisme_demandeur>
      <Adresse coordonnees="48.853917,2.357191" date_debut="2016-04-06" date_fin="2016-04-06">18  RUE  DE L'HOTEL DE VILLE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>MON POUSSIN</Titre>
      <Realisateur>FREDERIC FORESTIER</Realisateur>
      <Organisme_demandeur>LES FILMS DU 24</Organisme_demandeur>
      <Adresse coordonnees="48.852803,2.353543" date_debut="2016-03-15" date_fin="2016-03-15">4  RUE  JEAN DU BELLAY</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>MARIAGE BLANC</Titre>
      <Realisateur>TAREK BOUDALI</Realisateur>
      <Organisme_demandeur>AXEL FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.857944,2.358439" date_debut="2016-08-25" date_fin="2016-08-25">RUE  DU MARCHE DES BLANCS MANTEAUX</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>ON THE FRENCH RIVIERA</Titre>
      <Realisateur>ALAN SWYER</Realisateur>
      <Organisme_demandeur>BELLE EPOQUE FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.854578,2.350453" date_debut="2016-08-29" date_fin="2016-08-29">RUE  DE LA COLOMBE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>LA NUIT A DEVORE LE MONDE</Titre>
      <Realisateur>DOMINIQUE ROCHER</Realisateur>
      <Organisme_demandeur>HAUT ET COURT</Organisme_demandeur>
      <Adresse coordonnees="48.857724,2.353853" date_debut="2016-12-21" date_fin="2016-12-22">34  RUE  DE LA VERRERIE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>LA DOULEUR</Titre>
      <Realisateur>EMMANUEL FINKIEL</Realisateur>
      <Organisme_demandeur>LES FILMS DU POISSON</Organisme_demandeur>
      <Adresse coordonnees="48.852776,2.351614" date_debut="2016-09-02" date_fin="2016-09-02">1  PLACE  DE NOTRE DAME</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>IN AMERICA</Titre>
      <Realisateur>VINCENT PRIMAULT</Realisateur>
      <Organisme_demandeur>MAKING PROD</Organisme_demandeur>
      <Adresse coordonnees="48.858275,2.353421" date_debut="2016-04-11" date_fin="2016-04-11">14  RUE  DU TEMPLE (BHV)</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>LE REDOUTABLE</Titre>
      <Realisateur>MICHEL HAZANAVICIUS</Realisateur>
      <Organisme_demandeur>LES COMPAGNONS DU CINEMA</Organisme_demandeur>
      <Adresse coordonnees="48.851204,2.366481" date_debut="2016-08-24" date_fin="2016-08-24">RUE  DE L'ARSENAL</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>CHRONIQUES PARISIENNES</Titre>
      <Realisateur>ZABOU BREITMAN</Realisateur>
      <Organisme_demandeur>LES FILMS DU KIOSQUE</Organisme_demandeur>
      <Adresse coordonnees="48.854714,2.354821" date_debut="2016-10-01" date_fin="2016-10-01">PARVIS  DE L'HOTEL DE VILLE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LEO MATTEI/14 ET 15</Titre>
      <Realisateur>NICOLAS HERDT</Realisateur>
      <Organisme_demandeur>LGM CINEMA</Organisme_demandeur>
      <Adresse coordonnees="0" date_debut="2016-10-04" date_fin="2016-10-04">1  PARVIS  DE NOTRE DAME (HOTEL DIEU)</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LEBOWITZ CONTRE LEBOWITZ/9 A 12</Titre>
      <Realisateur>CHRISTOPHE BARRAUD</Realisateur>
      <Organisme_demandeur>CHABRAQUE PRODUCTIONS</Organisme_demandeur>
      <Adresse coordonnees="48.854852,2.345722" date_debut="2016-10-24" date_fin="2016-10-24">4  BOULEVARD  DU PALAIS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>UNE VIE VIOLENTE</Titre>
      <Realisateur>THIERRY DE PERRETI</Realisateur>
      <Organisme_demandeur>LES FILMS VELVET</Organisme_demandeur>
      <Adresse coordonnees="48.856108,2.353209" date_debut="2016-06-16" date_fin="2016-06-16">3  RUE  LOBAU</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>LE REDOUTABLE</Titre>
      <Realisateur>MICHEL HAZANAVICIUS</Realisateur>
      <Organisme_demandeur>LES COMPAGNONS DU CINEMA</Organisme_demandeur>
      <Adresse coordonnees="48.85194,2.365872" date_debut="2016-08-18" date_fin="2016-08-18">RUE  DE LA CERISAIE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>ALICE NEVERS, LE JUGE EST UNE FEMME/84 ET 85</Titre>
      <Realisateur>ERIC LE ROUX</Realisateur>
      <Organisme_demandeur>EGO PRODUCTION</Organisme_demandeur>
      <Adresse coordonnees="48.857972,2.352876" date_debut="2016-10-13" date_fin="2016-10-13">RUE  DE LA VERRERIE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>ON THE FRENCH RIVIERA</Titre>
      <Realisateur>ALAN SWYER</Realisateur>
      <Organisme_demandeur>BELLE EPOQUE FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.853542,2.347221" date_debut="2016-08-29" date_fin="2016-08-29">PARVIS  DE NOTRE DAME</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>STARS 80 LA SUITE</Titre>
      <Realisateur>THOMAS LANGMANN</Realisateur>
      <Organisme_demandeur>LA PETITE REINE</Organisme_demandeur>
      <Adresse coordonnees="48.851648,2.354284" date_debut="2016-09-19" date_fin="2016-09-19">QUAI  D'ORLEANS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>JUST DIVORCED</Titre>
      <Realisateur>MAXIME GOVARE</Realisateur>
      <Organisme_demandeur>LES IMPRODUCTIBLES</Organisme_demandeur>
      <Adresse coordonnees="48.854978,2.365625" date_debut="2016-10-06" date_fin="2016-10-06">PLACE  DES VOSGES</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BARBARA</Titre>
      <Realisateur>MATHIEU AMALRIC</Realisateur>
      <Organisme_demandeur>WAITING FOR CINEMA</Organisme_demandeur>
      <Adresse coordonnees="48.853792,2.350685" date_debut="2016-11-28" date_fin="2016-11-28">PONT  AU CHANGE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>IRIS/EX CHAOS</Titre>
      <Realisateur>JALIL LESPERT</Realisateur>
      <Organisme_demandeur>WY PRODUCTIONS</Organisme_demandeur>
      <Adresse coordonnees="48.857551,2.360897" date_debut="2016-02-18" date_fin="2016-02-18">RUE  DES FRANCS BOURGEOIS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LE BUREAU DES LEGENDES/SAISON 2 N°1 A 8</Titre>
      <Realisateur>ERIC ROCHANT</Realisateur>
      <Organisme_demandeur>THE OLIGARCHS PRODUCTIONS</Organisme_demandeur>
      <Adresse coordonnees="48.853036,2.355069" date_debut="2016-01-19" date_fin="2016-01-19">QUAI  BOURBON</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="TELEFILM">
      <Titre>LA BETE CURIEUSE</Titre>
      <Realisateur>LAURENT PERREAU</Realisateur>
      <Organisme_demandeur>EX NIHILO</Organisme_demandeur>
      <Adresse coordonnees="48.854671,2.347805" date_debut="2016-05-09" date_fin="2016-05-09">5  RUE  DE LA CITE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>ALIBI.COM</Titre>
      <Realisateur>PHILIPPE LACHEAU</Realisateur>
      <Organisme_demandeur>FECHNER FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.854299,2.366394" date_debut="2016-05-09" date_fin="2016-05-10">3  COUR  BERARD</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>ALICE NEVERS, LE JUGE EST UNE FEMME/82 ET 83</Titre>
      <Realisateur>ERIC LE ROUX</Realisateur>
      <Organisme_demandeur>EGO PRODUCTION</Organisme_demandeur>
      <Adresse coordonnees="48.851372,2.358107" date_debut="2016-04-05" date_fin="2016-04-05">QUAI  D'ANJOU/R POULLETIER (ANGLE)</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>ENGRENAGES SAISON 6/N° 7 A 12</Titre>
      <Realisateur>FREDERIC MERMOUD</Realisateur>
      <Organisme_demandeur>SON ET LUMIERE</Organisme_demandeur>
      <Adresse coordonnees="48.851849,2.356353" date_debut="2016-10-31" date_fin="2016-10-31">PONT  SAINT LOUIS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>THE AFFAIR</Titre>
      <Realisateur>JEFFREY REINER</Realisateur>
      <Organisme_demandeur>GEM FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.855335,2.355315" date_debut="2016-12-06" date_fin="2016-12-06">RUE  DES BARRES</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LIANG SHENG</Titre>
      <Realisateur>LIU CHUN-CHIEN</Realisateur>
      <Organisme_demandeur>KANZAMAN FRANCE</Organisme_demandeur>
      <Adresse coordonnees="48.857112,2.357911" date_debut="2016-12-13" date_fin="2016-12-13">RUE  DU TRESOR</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>TELLE MERE TELLE FILLE</Titre>
      <Realisateur>NOEMIE SAGLIO</Realisateur>
      <Organisme_demandeur>PAN EUROPENNE PRODUCTION</Organisme_demandeur>
      <Adresse coordonnees="48.855991,2.346972" date_debut="2016-07-18" date_fin="2016-07-19">2  QUAI  DE LA MEGISSERIE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="TELEFILM">
      <Titre>LA BETE CURIEUSE</Titre>
      <Realisateur>LAURENT PERREAU</Realisateur>
      <Organisme_demandeur>EX NIHILO</Organisme_demandeur>
      <Adresse coordonnees="48.854031,2.34943" date_debut="2016-05-09" date_fin="2016-05-09">8  RUE  D'ARCOLE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>NUMERO UNE</Titre>
      <Realisateur>TONIE MARSHALL</Realisateur>
      <Organisme_demandeur>TABO TABO FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.853792,2.350685" date_debut="2016-10-18" date_fin="2016-10-18">RUE  CHANOINESSE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>MARYLINE</Titre>
      <Realisateur>GUILLAUME GALLIENNE</Realisateur>
      <Organisme_demandeur>LGM FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.85427,2.35111" date_debut="2016-09-07" date_fin="2016-09-07">RUE  DES URSINS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>MON POUSSIN</Titre>
      <Realisateur>FREDERIC FORESTIER</Realisateur>
      <Organisme_demandeur>LES FILMS DU 24</Organisme_demandeur>
      <Adresse coordonnees="48.851793,2.356794" date_debut="2016-03-15" date_fin="2016-03-15">46  RUE  SAINT LOUIS EN L'ILE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>L'EMBARRAS DU CHOIX</Titre>
      <Realisateur>ERIC DELAVAINE</Realisateur>
      <Organisme_demandeur>SOMBRERO PRODUCTIONS</Organisme_demandeur>
      <Adresse coordonnees="48.851849,2.356353" date_debut="2016-08-09" date_fin="2016-08-09">PONT  SAINT LOUIS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>RED OAKS</Titre>
      <Realisateur>HALL HARTLEY</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.854994,2.35817" date_debut="2016-08-05" date_fin="2016-08-05">12  RUE  DE JOUY</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>LIANG SHENG</Titre>
      <Realisateur>LIU CHUN-CHIEN</Realisateur>
      <Organisme_demandeur>KANZAMAN FRANCE</Organisme_demandeur>
      <Adresse coordonnees="48.859679,2.350575" date_debut="2016-12-13" date_fin="2016-12-13">RUE  SAINT MARTIN</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>MARVIN</Titre>
      <Realisateur>ANNE FONTAINE</Realisateur>
      <Organisme_demandeur>CINE @</Organisme_demandeur>
      <Adresse coordonnees="48.85723,2.355111" date_debut="2016-09-02" date_fin="2016-09-02">10  RUE  DE LA VERRERIE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>IN AMERICA</Titre>
      <Realisateur>VINCENT PRIMAULT</Realisateur>
      <Organisme_demandeur>MAKING PROD</Organisme_demandeur>
      <Adresse coordonnees="48.855368,2.355793" date_debut="2016-04-06" date_fin="2016-04-06">PONT  LOUIS PHILIPPE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>ENGRENAGES SAISON 6/N° 7 A 12</Titre>
      <Realisateur>FREDERIC MERMOUD</Realisateur>
      <Organisme_demandeur>SON ET LUMIERE</Organisme_demandeur>
      <Adresse coordonnees="48.852751,2.351975" date_debut="2016-10-31" date_fin="2016-10-31">2  RUE  DU CLOITRE NOTRE DAME</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>CHEFS - SAISON 2</Titre>
      <Realisateur>ARNAUD MALHERBE</Realisateur>
      <Organisme_demandeur>CALT PRODUCTION</Organisme_demandeur>
      <Adresse coordonnees="48.851849,2.356353" date_debut="2016-04-25" date_fin="2016-04-25">PONT  SAINT LOUIS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>NUMERO UNE</Titre>
      <Realisateur>TONIE MARSHALL</Realisateur>
      <Organisme_demandeur>TABO TABO FILMS</Organisme_demandeur>
      <Adresse coordonnees="48.852279,2.351269" date_debut="2016-10-18" date_fin="2016-10-18">SQUARE  JEAN XXIII</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>RED OAKS</Titre>
      <Realisateur>HALL HARTLEY</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.855335,2.355315" date_debut="2016-08-05" date_fin="2016-08-05">RUE  DES BARRES</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="TELEFILM">
      <Titre>LA BETE CURIEUSE</Titre>
      <Realisateur>LAURENT PERREAU</Realisateur>
      <Organisme_demandeur>EX NIHILO</Organisme_demandeur>
      <Adresse coordonnees="48.854342,2.347729" date_debut="2016-05-09" date_fin="2016-05-09">1  PARVIS  NOTRE DAME</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>NUMERO UNE</Titre>
      <Realisateur>TONIE MARSHALL</Realisateur>
      <Organisme_demandeur>TABO TABO FILMS</Organisme_demandeur>
      <Adresse coordonnees="0" date_debut="2016-11-16" date_fin="2016-11-18">PARVIS  DE NOTRE DAME (HOTEL DIEU)</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.853405,2.358201" date_debut="2016-04-30" date_fin="2016-04-30">CITE  INTERNATIONALE DES ARTS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>ENGRENAGES/SAISON 6/N° 1 A 6</Titre>
      <Realisateur>FREDERIC JARDIN</Realisateur>
      <Organisme_demandeur>SON ET LUMIERE</Organisme_demandeur>
      <Adresse coordonnees="48.857551,2.360897" date_debut="2016-06-15" date_fin="2016-06-15">2  RUE  DES FRANCS BOURGEOIS</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="SERIE_TELEVISEE">
      <Titre>CHEFS - SAISON 2</Titre>
      <Realisateur>ARNAUD MALHERBE</Realisateur>
      <Organisme_demandeur>CALT PRODUCTION</Organisme_demandeur>
      <Adresse coordonnees="48.854952,2.354511" date_debut="2016-07-02" date_fin="2016-07-02">82  RUE  DE L'HOTEL DE VILLE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>
      <Organisme_demandeur>FIRSTEP</Organisme_demandeur>
      <Adresse coordonnees="48.855617,2.363093" date_debut="2016-02-26" date_fin="2016-02-26">RUE  DE JARENTE</Adresse>
    </Tournage>
  </Arrondissement>
  <Arrondissement>
    75004
    <Tournage type="LONG_METRAGE">
      <Titre>BEFIKRE</Titre>
      <Realisateur>ADITYA CHOPRA</Realisateur>