=== MLOPEZMALET/documents-structures/exemples/exemples-dtd/exemple_entites.dtd
<?xml encoding="UTF-8"?>

<!--Déclaration d'une entité XML 'maison-edition'
    ayant pour valeur 'La Volte'
    
    Elle peut être utilisée dans un document XML
    qui sera associée à cette DTD
    
    L'appel de l'entité est '&maison-edition;'
-->
<!ENTITY maison-edition "La Volte">

<!--Déclaration d'une entité paramétrique appelée 'isbn'
    Ne pas oublier le '%' avant d'introduire le nom
    
    Elle permet de remplacer en un appel, la déclaration
    de l'attribut 'isbn' en indiquant son type et son obligation
    Cet appel se fera dans la DTD (voir ligne 31)
-->
<!ENTITY % isnb "isbn NMTOKEN #REQUIRED">

<!ELEMENT bibliographie (auteur)>

<!ELEMENT auteur (livre)+>
<!ATTLIST auteur
  nom NMTOKEN #REQUIRED
  prenom NMTOKEN #REQUIRED>

<!ELEMENT livre (titre,edition?,datePublication)>
<!ATTLIST livre
  %isnb;>

<!ELEMENT titre (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT datePublication (#PCDATA)>

=== MLOPEZMALET/documents-structures/exemples/exemples-dtd/exemple_entites.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bibliographie SYSTEM "exemple_entites.dtd">

<!--Dans la DTD exemple_entites.dtd, déclaration de l'entité
    <!ENTITY maison-edition "La Volte">
-->

<!--Important: les navigateurs ne chargent pas les entités
    externes lors de la visualisation du document XML
    entraînant une erreur
-->

<bibliographie>
    <auteur nom="Damasio" prenom="Alain">
        
        <livre isbn="2-84358-095-1">
            <titre>La Zone du Dehors</titre>
            <edition>Cylibris</edition>
            <datePublication>1999</datePublication>
        </livre>
        <livre isbn="978-2-9522217-0-2">
            <titre>La Horde du Contrevent</titre>
            <edition>&maison-edition;</edition>
            <datePublication>2004</datePublication>
        </livre>
        <livre isbn="978-2-37049-074-2">
            <titre>Les Furtifs</titre>
            <edition>&maison-edition;</edition>
            <datePublication>2019</datePublication>
        </livre>
        
    </auteur>

</bibliographie>
